### ISSUE TITLE
why adding 1 to class_ids after gathering valid size and inside box?

### ISSUE THREAD

**Issue by leasueparis** [AI-UI-GmbH/AI-Lab#1]
matched_class_ids = tf.reshape(tf.gather(class_ids, box_indices) + 1, (-1,))

**Comment by PengchengFan** [comment]
Hi @leasueparis , because class_id 0 is reserved for background.

**Comment by leasueparis** [comment]
Thanks. So it is devised to treat with such case that there will be some annotated objects with bbox and labeled as background in the training set, right?

**Comment by PengchengFan** [comment]
In the label encoding phase, all class ids will be automatically plus 1. If an object is annotated as "background" or "BG" etc., it is also treated as a label not as background.

**Comment by leasueparis** [comment]
Got it. Thanks for your kind reply.
